name: Run Discord Bot Every Minute

on:
  schedule:
    - cron: "* * * * *"  # Runs every minute
  workflow_dispatch:      # Allows manual trigger

concurrency:
  group: discord-bot-singleton
  cancel-in-progress: true  # Prevent multiple overlapping runs

jobs:
  run-bot:
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TOKEN }}
      API_KEY: ${{ secrets.API_KEY }}  # Add more secrets as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        run: python main.py
